export enum UserState {

    WAITING_LICENSE = "WAITING_LICENSE",

    WAITING_GROUP = "WAITING_GROUP",

    WAITING_BACKEND = "WAITING_BACKEND",

    WAITING_FIREBASE_JSON = "WAITING_FIREBASE_JSON",

    WAITING_FIREBASE_URL = "WAITING_FIREBASE_URL",

    WAITING_FIREBASE_AUTH = "WAITING_FIREBASE_AUTH",

    WAITING_VPS = "WAITING_VPS",

    WAITING_DEVICE = "WAITING_DEVICE",

    READY = "READY"

}