export enum UserState {

    IDLE = "IDLE",

    WAITING_LICENSE = "WAITING_LICENSE",

    WAITING_FIREBASE = "WAITING_FIREBASE",

    WAITING_VPS = "WAITING_VPS",

    WAITING_DEVICE = "WAITING_DEVICE",

    WAITING_GROUP = "WAITING_GROUP"

}